### ISSUE TITLE
System.NullReferenceException

### ISSUE THREAD

**Issue by CCCCCCHARA** [Juzlus/VPet.Plugin.ScratchCard#1]
![QQ20240929-174310](https://github.com/user-attachments/assets/47fe1421-f423-47f6-a729-0d9abffc0e8c)

**Comment by CCCCCCHARA** [comment]
Maybe you can use this way to bind events: https://github.com/LorisYounger/VPet/commit/32f11dbe7d19c6ca7a83a2d1290dc6dcbdc7f0f2

**Comment by CCCCCCHARA** [comment]
I tried to run it on 2 win10 pc but neither worked

**Comment by Juzlus** [comment]
MainWindow and winBetterBuy have different Event_TakeItem, so I can't rely on it. (I tested it in the early stages).
Do you get this error normally or only when debugging, maybe it is a different index in your case.

I made an automatic index search I hope it will work. https://github.com/Juzlus/VPet.Plugin.ScratchCard/commit/6d1760c02ab6a486a2d3b96addc75fe90e3b5f8e

**Comment by CCCCCCHARA** [comment]
OK, it works

And I think this is an example of using Event_TakeItem:
```
public override void LoadPlugin()
{
   MW.Event_TakeItem += Eat;
}

public void Eat(Food food)
{
    MW.Main.Say(food.Name);
}

```

**Comment by Juzlus** [comment]
Good to hear that.

About Event_TakeItem I know what the code looks like, but when I tested it didn't respond to buying an item, so I think winBetterBuy is using a different instance.

I will update this mod and others based on Application.Current within 24 hours.
